// SPDX-License-Identifier: Apache-2.0

package runner

import (
	"fmt"
	"strings"
)

// WrapperHost is what a host contributes to the generated wrapper: where the file goes,
// and how that host names the two ends of the commit range.
//
// Those two expressions are the parameters WP10 asks the generator to take from the
// start although there is one wrapper to generate. They are the only host specific
// thing in it, so another host is an entry in this table rather than a second generator.
type WrapperHost struct {
	ID      string
	Path    string
	BaseRef string
	HeadRef string
	render  func(WrapperHost, string) string
}

var wrapperHosts = map[string]WrapperHost{
	"github": {
		ID:      "github",
		Path:    ".github/workflows/xeno-gate.yml",
		BaseRef: "${{ github.event.pull_request.base.sha }}",
		HeadRef: "${{ github.event.pull_request.head.sha }}",
		render:  renderGitHub,
	},
}

// WrapperHosts lists what can be generated, for an error that helps.
func WrapperHosts() []string { return []string{"github"} }

// Wrapper generates the CI wrapper for a host.
//
// It calls one command and does nothing else. A wrapper that built or tested would be
// this project's own pipeline, which is a different file with the opposite purpose, and
// mixing them up puts build steps into a template or a gate call into a pipeline.
func Wrapper(host, phase, runnerVersion string) (WrapperHost, string, error) {
	h, ok := wrapperHosts[host]
	if !ok {
		return h, "", fmt.Errorf("no wrapper for host %q; there is %s", host, strings.Join(WrapperHosts(), ", "))
	}
	return h, h.render(h, runnerVersion), nil
}

func renderGitHub(h WrapperHost, runnerVersion string) string {
	return fmt.Sprintf(`# Generated by xeno init. It calls one command and does nothing else: this is the
# wrapper, not the project's own pipeline, and a build step here would be in the wrong
# file.
#
# Both ends of the commit range are passed rather than derived. A CI system may check
# out a merge commit it produced itself, and a runner that took that for the head would
# judge a commit nobody wrote.
#
# CI recomputes and compares. It writes nothing, which is why the phase has to carry its
# gate.yaml into the repository before the push.
name: xeno gate

on:
  pull_request:

permissions:
  contents: read

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0   # both ends of the range have to be reachable

      - name: install the pinned runner
        run: |
          # The version is pinned because a different runner produces a different hash
          # or a different verdict than the local run it is comparing against.
          echo "install xeno %s here"

      - name: verify
        run: |
          xeno gate verify

      # One call per phase the change touches. --phase is filled in per repository;
      # what is fixed here is that both ends of the range are passed.
      - name: gate
        run: |
          xeno gate run --intent "$XENO_INTENT" --phase "$XENO_PHASE" \
            --base %s \
            --head %s
`, runnerVersion, h.BaseRef, h.HeadRef)
}
